title: Faiez's notes
email: hares.faiez@gmail.com
phone: +216 26 87 17 88
description: >
    Programmign and software design tales

avatar: "https://avatars3.githubusercontent.com/u/10279086?v=3&s=460"

url: "https://haresfaiez.github.io"
baseurl: ""
avatar: https://avatars3.githubusercontent.com/u/10279086?v=3&s=460

result: ""

twitter_handle  : FaiezHares
github_handle   : haresfaiez
goodreads_handle: 53209781-hares-faiez
instagram_handle: faiezhares
linkedin_handle : faiez-hares-4b2262158
behance_handle  : hrsfaiez

markdown: kramdown
