title: Faiez Hares
email: hares.faiez@gmail.com
phone: +216 26 87 17 88
description: >
    Programming and software design tales

avatar: "https://avatars3.githubusercontent.com/u/10279086?v=3&s=460"

url: "https://haresfaiez.github.io"
baseurl: ""
avatar: https://avatars3.githubusercontent.com/u/10279086?v=3&s=460
resume: https://docs.google.com/document/d/19jbbcrvdfAr6aiSlDY3h9OI1zoiAm4uat8dTu8goEiI/edit?usp=sharing

result: ""

twitter_handle  : FaiezHares
github_handle   : haresfaiez
goodreads_handle: 53209781-hares-faiez
letterboxd_handle: faiezhares
linkedin_handle : faiez-hares-4b2262158

markdown: kramdown

sass:
  sass_dir: sass
  style: compressed
