title: Faiez Hares
email: hares.faiez@gmail.com
description: >
    Programming and software design tales


url: "https://haresfaiez.github.io"
baseurl: ""

mastodon_handle : faiezhares
twitter_handle  : FaiezHares
github_handle   : haresfaiez
goodreads_handle: 53209781-hares-faiez
letterboxd_handle: faiezhares
linkedin_handle : faiez-hares-4b2262158

markdown: kramdown

sass:
  sass_dir: sass
  style: compressed
