title: Faiez Hares
email: hares.faiez@gmail.com
description: >
    Programming and software design tales


url: "https://haresfaiez.github.io"
baseurl: ""

mastodon_handle : faiezhares
bsky_handle  : faiezhares
goodreads_handle: 53209781-hares-faiez
linkedin_handle : faiez-hares-4b2262158

markdown: kramdown

sass:
  sass_dir: sass
  style: compressed
